### ISSUE TITLE
How to select the filters?

### ISSUE THREAD

**Issue by Dandelion111** [AngeloUNIMI/PalmNet#3]
Hello, I am a little confused about the paper. After getting Sm, how to extract 5 filters, could you please explain in detail?Thank you very much!

**Comment by AngeloUNIMI** [comment]
hi, you probably want to take a look at this function
https://github.com/AngeloUNIMI/PalmNet/blob/master/functions_Gabor/findBestWaveletsTesting.m

**Comment by Dandelion111** [comment]
Thank you for your reply!I've seen this function, another function within this function: "getMostUsedWavelets", there's one thing I've been wondering about, I think currX, currY, currO will be unique every time ind is added, when is tmpRes going to be equal to 1 in line 23 of the if statement?

**Comment by Dandelion111** [comment]
How should I interpret this sentence that considering each filter at
most once for each position in the ROI.

**Comment by Dandelion111** [comment]
In Sm of size A*u*v, each filter in Ga is used once. Why don't they have the same number in Sm?

**Comment by AngeloUNIMI** [comment]
in the function "getMostUsedWavelets", we cycle through the filter responses in decreasing order of magnitude. The variable tmpRes keeps track of whether we already considered the filter at a particular image position. A particular combination of currX, currY, curr might happen more times, after the first time the corresponding value of tmpRes will be = 1.

**Comment by Dandelion111** [comment]
Can I understand that there are 114 currX, curries, currs at a particular location in ROI?

**Comment by Dandelion111** [comment]
The size of Sm is A*u*v, while there are A*u*v positions in tmpRes, which are exactly one-to-one correspondence. Why do we repeatedly consider the same position?

**Comment by Dandelion111** [comment]
Please forgive my stupidity!

**Comment by AngeloUNIMI** [comment]
> The size of Sm is A_u_v, while there are A_u_v positions in tmpRes, which are exactly one-to-one correspondence. Why do we repeatedly consider the same position?

Feel free to optimize the code if possible ;)

**Comment by Dandelion111** [comment]
Hello, may I ask why these unrecognized characters are added to the verification program?
<<<<<<< HEAD
=======
>>>>>>> 5aa7404d46b056250a68745e148af098f5e8a28e
