### ISSUE TITLE
180-centers,why?

### ISSUE THREAD

**Issue by Dandelion111** [AngeloUNIMI/PalmNet#4]
Hello, may I ask you a question? In the "searchGaborOrientation" code, on line 53, why do you subtract the centers from 180?Don't use 180 minus centers just the right bin?

**Comment by AngeloUNIMI** [comment]
it's a conversion to anti-clockwise, probably for compatibility with some other function

**Comment by Dandelion111** [comment]
Thanks for sharing, but I feel like line 53 should be removed
