### ISSUE TITLE
Doubt regarding the selection of the most used wavelets (functions_Gabor/getMostUsedWavelets.m)

### ISSUE THREAD

**Issue by pannagas18** [AngeloUNIMI/PalmNet#6]
Hey thank you for this code and I appreciate taking your time to read this. I came across your paper about PalmNet in [(IEEE)](https://ieeexplore.ieee.org/document/8691498) and it sounded very intriguing. So I was just looking through your code and I had a doubt in it. Please correct me if my understanding of this is wrong.

functions_Gabor/getMostUsedWavelets.m
In the above file, there is this snippet of code:
```
    %get information of corresponding wavelet
    currX = sortRes(ind, 4);
    currY = sortRes(ind, 5);
    currO = sortRes(ind, 6);
    
    %check if current wavelet at current position already
    %used
    if (tmpRes(currO).value(currY, currX) == 1)
        %increment counter
        ind = ind + 1;
        continue
    end %if (tmpRes(currY, currX, currO)
```

I assume it refers to this line from the paper: 

> Then, for each filter in Ga, we count the number of corresponding responses in sm, considering each filter at most once for each position (x, y) in the ROI.

But, doesn't sortRes contain a unique combination of O, X and Y? What I'm trying to say is in tmpRes, there'd be no value equal to 1 when that condition is being checked and that combination of O, X and Y would have never appeared before. 

Please let me know if my understanding is wrong. Thank you for the code and once again I appreciate your time.

**Comment by AngeloUNIMI** [comment]
hi, thank you for the interest in our code, but infortunately it's been a while since I coded it and I haven't worked on it since.

**Comment by pannagas18** [comment]
Hey, thank you for your reply. I actually found a similar doubt in one of the closed [issues.](https://github.com/AngeloUNIMI/PalmNet/issues/3) Thank you for your time!
